Converge Architecture: routes Namespace Reference
routes Namespace Reference
Functions
not_found (error)
bad_request (error)
internal_error (error)
forward (baseUrl, endpoint, method, data=None)
get_gnb_placement_status (gnbId)
setup_gnb_placement (gnbId)
get_gnb_radio_communications_status (gnbId)
setup_gnb_radio_communications (gnbId)
get_gnb_radio_sensing_status (gnbId)
setup_gnb_radio_sensing (gnbId)
get_gnb_video_sensing_status (gnbId)
setup_gnb_video_sensing (gnbId)
get_gnb_xapp_status (id)
upload_gnb_xapp (id)
get_ue_placement_status (ueId)
setup_ue_placement (ueId)
get_ue_radio_communications_status (ueId)
setup_ue_radio_communications (ueId)
get_ue_radio_sensing_status (ueId)
setup_ue_radio_sensing (ueId)
get_ue_video_sensing_status (ueId)
setup_ue_video_sensing (ueId)
get_lis_placement_status (lisId)
setup_lis_placement (lisId)
get_lis_radio_communications_status (lisId)
setup_lis_radio_communications (lisId)
get_lis_radio_sensing_status (lisId)
setup_lis_radio_sensing (lisId)
get_lis_video_sensing_status (lisId)
setup_lis_video_sensing (lisId)
get_ctcf_status (ctcfId)
control_ctcf (command, ctcfId)
get_ctcf_rules (ctcfId)
setup_ctcf_rules (ctcfId)
get_ctcf_telemetry (ctcfId)
get_nets_status ()
setup_nets ()
upload_ml_model ()
download_ml_model ()
download_odr_dataset ()
upload_odr_dataset ()
get_experiment_status ()
gnb_control_start (command, gnbId)
CgNB Start/Stop CgNB sends Start/Stop command to NT-RIC, O-CU, O-DU and O-RU.
get_gnb_configuration (gnbId)
CgNB Configuration Status Get the current CgNB configuration.
get_gnb_status (gnbId)
CgNB Status Get the current CgNB status.
configure_radio_comms (gnbId)
CgNB Reconfiguration CgNB creates and sends a reconfiguration command via CgNB interface to O-CU, O-DU, O-RU and NT-RIC.
not_found (error)
bad_request (error)
internal_error (error)
control_placement (command, lisId)
configure_placement (lisId)
get_placement_configuration (lisId)
get_placement_status (lisId)
control_radio_comms (command, lisId)
radio_comms_feedback (lisId)
get_radio_comms_configuration (lisId)
get_radio_comms_status (lisId)
control_radio_sensing (command, lisId)
configure_radio_sensing (lisId)
get_radio_sensing_status (lisId)
traffic_control_start (command, ctcfId)
CTCF sends a start/stop command to control traffic servers.
get_traffic_control_rules (ctcfId)
Get the current traffic control rules configuration.
add_traffic_control_rules (ctcfId)
Add or modify traffic control rules.
get_traffic_statistics (ctcfId)
Get statistics related to traffic control.
ue_control_start (command, ueId)
CUECF sends Start/Stop command via CUE interface to the relevant UE.
get_ue_configuration (ueId)
Get the current CUE configuration.
get_ue_status (ueId)
Get the current CUE status.
cvf_control_start (command, cameraId)
CVCF sends a start/stop command to the cameras.
configure_camera (cameraId)
Set camera configuration based on its ID.
get_camera_status (cameraId)
Get camera status.
get_camera_configuration (cameraId)
Get camera configuration.
visual_model_control_start (command, modelId)
CVCF sends a start/stop command to activate/deactivate support vision model.
configure_visual_model (modelId)
Set support vision model configuration based on its ID.
get_vision_model_configuration (modelId)
Get support vision model configuration.
get_vision_model_status (modelId)
Get support vision model status.
Variables
app = Flask(__name__)
dict gnb_data_store
dict ue_data_store
dict ctcf_data_store = {}
dict simulator_data_store = {}
dict ml_model_store = {}
dict odr_dataset_store = {}
dict experiment_status_store = {}
str CLISCF_API_BASE_URL = "http://localhost:5001"
str CTCF_API_BASE_URL = "http://localhost:5002"
str CgNBCF_API_BASE_URL = "http://localhost:5003"
debug
dict cgnbcf_data_store
dict cliscf_data_store
Function Documentation
add_traffic_control_rules()
routes.add_traffic_control_rules (ctcfId)
Add or modify traffic control rules.
Parameters
ctcfId The ID of the CTCF.
Returns
JSON response with the result of the configuration.
Definition at line 94 of file routes.py.
def add_traffic_control_rules(ctcfId):
    ctcf_data_store.setdefault(ctcfId, {})['ctcf_rules'] = request.json
    return jsonify({"result": "Traffic Control Rules configuration successful"}), 201
bad_request() [1/2]
routes.bad_request (error)
@brief Handles 400 errors.
@param error The error object.
@return JSON response with error details.
Definition at line 44 of file routes.py.
def bad_request(error):
    problem = {
        'error' : {
            'type' : "",
            'title' : "Bad Request",
            'status' : 400,
            'detail' : "The request could not be understood or was missing required parameters.",
            'instance' : request.url
        }
    }
    return jsonify(problem), 400
@app.errorhandler(500)
Referenced by control_ctcf(), control_placement(), control_radio_comms(), control_radio_sensing(), cvf_control_start(), gnb_control_start(), traffic_control_start(), ue_control_start(), and visual_model_control_start().
bad_request() [2/2]
routes.bad_request (error)
@brief Handles 400 errors.
@param error The error object.
@return JSON response with error details.
Definition at line 39 of file routes.py.
def bad_request(error):
    """
    @brief Handles 400 errors.
    @param error The error object.
    @return JSON response with error details.
    """
    problem = {
        'error': {
            'type': "",
            'title': "Bad Request",
            'status': 400,
            'detail': "The request could not be understood or was missing required parameters.",
            'instance': request.url
        }
    }
    return jsonify(problem), 400
@app.errorhandler(500)
configure_camera()
routes.configure_camera (cameraId)
Set camera configuration based on its ID.
Parameters
cameraId The ID of the camera.
Returns
JSON response with the result of the configuration.
Definition at line 80 of file routes.py.
def configure_camera(cameraId):
    cvf_data_store.setdefault(cameraId, {})['camera_configuration'] = request.json
    return jsonify({"result": "Camera reconfiguration successful"}), 201
configure_placement()
routes.configure_placement (lisId)
@brief Configures the placement position of the LIS.
@param lisId The ID of the LIS.
@return JSON response with the result of the configuration.
Definition at line 88 of file routes.py.
def configure_placement(lisId):
    """
    @brief Configures the placement position of the LIS.
    @param lisId The ID of the LIS.
    @return JSON response with the result of the configuration.
    """
    cliscf_data_store.setdefault(lisId, {})['placement_configuration'] = request.json
    return jsonify({"result": "Placement configuration successful"}), 201
@app.route('/configuration/placement/<int:lisId>', methods=['GET'])
configure_radio_comms()
routes.configure_radio_comms (ueId)
CgNB Reconfiguration CgNB creates and sends a reconfiguration command via CgNB interface to O-CU, O-DU, O-RU and NT-RIC.
The CUECF creates and sends a reconfiguration command via CUE interface to the relevant UE.
@brief Creates and sends a reconfiguration command via CgNB interface to O-CU, O-DU, O-RU, and NT-RIC.
@param gnbId The ID of the gNB.
@return JSON response with the result of the reconfiguration.
@brief Configures the LIS radio communications.
@param lisId The ID of the LIS.
@return JSON response with the result of the configuration.
Parameters
ueId The ID of the UE.
Returns
JSON response with the result of the reconfiguration.
Definition at line 114 of file routes.py.
def configure_radio_comms(gnbId):
    """
    @brief Creates and sends a reconfiguration command via CgNB interface to O-CU, O-DU, O-RU, and NT-RIC.
    @param gnbId The ID of the gNB.
    @return JSON response with the result of the reconfiguration.
    """
    cgnbcf_data_store.setdefault(gnbId, {})['gnb_configuration'] = request.json
    return jsonify({"result": "gNB reconfiguration successful"}), 201
configure_radio_sensing()
routes.configure_radio_sensing (lisId)
@brief Configures the LIS radio sensing.
@param lisId The ID of the LIS.
@return JSON response with the result of the configuration.
Definition at line 180 of file routes.py.
def configure_radio_sensing(lisId):
    """
    @brief Configures the LIS radio sensing.
    @param lisId The ID of the LIS.
    @return JSON response with the result of the configuration.
    """
    cliscf_data_store.setdefault(lisId, {})['radio_sensing_configuration'] = request.json
    return jsonify({"result": "Radio sensing configuration successful"}), 201
@app.route('/configuration/radio-sensing/<int:lisId>/status', methods=['GET'])
configure_visual_model()
routes.configure_visual_model (modelId)
Set support vision model configuration based on its ID.
Parameters
modelId The ID of the vision model.
Returns
JSON response with the result of the configuration.
Definition at line 113 of file routes.py.
def configure_visual_model(modelId):
    vm_data_store.setdefault(modelId, {})['vision_model_configuration'] = request.json
    return jsonify({"result": "Vision Model reconfiguration successful"}), 201
control_ctcf()
routes.control_ctcf (command, ctcfId)
Definition at line 218 of file routes.py.
def control_ctcf(command, ctcfId):
    if command not in ['start', 'stop']:
        return bad_request(400)
    ctcf_data_store.setdefault(ctcfId, {})['control'] = command
    return forward(CTCF_API_BASE_URL,f"/control/{command}/{ctcfId}", 'POST', request.json)
@app.route('/api/v1/CTCF/configuration/<int:ctcfId>/rules', methods=['GET'])
References bad_request(), and forward().
control_placement()
routes.control_placement (command, lisId)
@brief Sends a Start/Stop command to initiate/stop movement of the LIS.
@param command The command to execute (start/stop).
@param lisId The ID of the LIS.
@return JSON response with the result of the command.
Definition at line 75 of file routes.py.
def control_placement(command, lisId):
    """
    @brief Sends a Start/Stop command to initiate/stop movement of the LIS.
    @param command The command to execute (start/stop).
    @param lisId The ID of the LIS.
    @return JSON response with the result of the command.
    """
    if command not in ['start', 'stop']:
        return bad_request("Invalid command")
    cliscf_data_store.setdefault(lisId, {})['placement_status'] = command
    return jsonify({"result": f"Placement {command} command executed successfully"}), 201
@app.route('/configuration/placement/<int:lisId>', methods=['POST'])
References bad_request().
control_radio_comms()
routes.control_radio_comms (command, lisId)
@brief Sends a Start/Stop command to deploy/reset the configured LIS radio communications.
@param command The command to execute (start/stop).
@param lisId The ID of the LIS.
@return JSON response with the result of the command.
Definition at line 116 of file routes.py.
def control_radio_comms(command, lisId):
    """
    @brief Sends a Start/Stop command to deploy/reset the configured LIS radio communications.
    @param command The command to execute (start/stop).
    @param lisId The ID of the LIS.
    @return JSON response with the result of the command.
    """
    if command not in ['start', 'stop']:
        return bad_request("Invalid command")
    cliscf_data_store.setdefault(lisId, {})['radio_comms_status'] = command
    return jsonify({"result": f"Radio communications {command} command executed successfully"}), 201
@app.route('/configuration/radio-comms/<int:lisId>', methods=['POST'])
References bad_request().
control_radio_sensing()
routes.control_radio_sensing (command, lisId)
@brief Sends a Start/Stop command to deploy/reset the configured radio sensing setup.
@param command The command to execute (start/stop).
@param lisId The ID of the LIS.
@return JSON response with the result of the command.
Definition at line 167 of file routes.py.
def control_radio_sensing(command, lisId):
    """
    @brief Sends a Start/Stop command to deploy/reset the configured radio sensing setup.
    @param command The command to execute (start/stop).
    @param lisId The ID of the LIS.
    @return JSON response with the result of the command.
    """
    if command not in ['start', 'stop']:
        return bad_request("Invalid command")
    cliscf_data_store.setdefault(lisId, {})['radio_sensing_status'] = command
    return jsonify({"result": f"Radio sensing {command} command executed successfully"}), 201
@app.route('/configuration/radio-sensing/<int:lisId>', methods=['POST'])
References bad_request().
cvf_control_start()
routes.cvf_control_start (command, cameraId)
CVCF sends a start/stop command to the cameras.
Parameters
command The command to execute (start/stop).
cameraId The ID of the camera.
Returns
JSON response with the result of the command.
Definition at line 70 of file routes.py.
def cvf_control_start(command, cameraId):
    if command not in ['start', 'stop']:
        return bad_request("Invalid command")
    cvf_data_store.setdefault(cameraId, {})['cvf_control'] = command
    return jsonify({"result": f"CV control {command} command executed successfully"}), 201
References bad_request().
download_ml_model()
routes.download_ml_model ()
Definition at line 254 of file routes.py.
def download_ml_model():
    return jsonify(ml_model_store.get('model', {})), 200
# ODR Dataset Endpoints
@app.route('/api/v1/ODR/downlink', methods=['GET'])
download_odr_dataset()
routes.download_odr_dataset ()
Definition at line 259 of file routes.py.
def download_odr_dataset():
    return jsonify(odr_dataset_store.get('dataset', {})), 200
@app.route('/api/v1/ODR/upload', methods=['POST'])
forward()
routes.forward (baseUrl, endpoint, method, data = None)
Definition at line 69 of file routes.py.
def forward(baseUrl,endpoint, method, data=None):
    url = f"{baseUrl}{endpoint}"
    try:
        if method == 'GET':
            response = requests.get(url)
        elif method == 'POST':
            response = requests.post(url, json=data)
        elif method == 'PUT':
            response = requests.put(url, json=data)
        elif method == 'DELETE':
            response = requests.delete(url)
        else:
            return jsonify({"error": "Unsupported method"}), 405
        response.raise_for_status()
        return jsonify(response.json()), response.status_code
    except requests.exceptions.RequestException as e:
        return jsonify({"error": str(e)}), 500
# gNB Endpoints
@app.route('/api/v1/gNB/placement-status/<int:gnbId>', methods=['GET'])
Referenced by control_ctcf(), get_ctcf_rules(), get_ctcf_status(), get_ctcf_telemetry(), get_gnb_placement_status(), get_lis_placement_status(), get_lis_radio_communications_status(), get_lis_radio_sensing_status(), get_lis_video_sensing_status(), setup_ctcf_rules(), setup_gnb_placement(), setup_lis_placement(), setup_lis_radio_communications(), setup_lis_radio_sensing(), and setup_lis_video_sensing().
get_camera_configuration()
routes.get_camera_configuration (cameraId)
Get camera configuration.
Parameters
cameraId The ID of the camera.
Returns
JSON response with the current configuration.
Definition at line 95 of file routes.py.
def get_camera_configuration(cameraId):
    return jsonify(cvf_data_store.get(cameraId, {}).get('camera_configuration', {})), 200
get_camera_status()
routes.get_camera_status (cameraId)
Get camera status.
Parameters
cameraId The ID of the camera.
Returns
JSON response with the current status.
Definition at line 88 of file routes.py.
def get_camera_status(cameraId):
    return jsonify(cvf_data_store.get(cameraId, {}).get('camera_status', {})), 200
get_ctcf_rules()
routes.get_ctcf_rules (ctcfId)
Definition at line 225 of file routes.py.
def get_ctcf_rules(ctcfId):
    return  forward(CTCF_API_BASE_URL,f"/configuration/{ctcfId}/rules", 'GET')
@app.route('/api/v1/CTCF/configuration/<int:ctcfId>/rules', methods=['POST'])
References forward().
get_ctcf_status()
routes.get_ctcf_status (ctcfId)
Definition at line 207 of file routes.py.
def get_ctcf_status(ctcfId):
    return forward(CTCF_API_BASE_URL,f"/configuration/placement/{ctcfId}/status",'GET')
'''
@app.route('/api/v1/CTCF/setup/<int:ctcfId>', methods=['POST'])
def setup_ctcf(ctcfId):
    ctcf_data_store.setdefault(ctcfId, {})['status'] = request.json
    return jsonify({"result": "CTCF setup successful"}), 201
'''
@app.route('/api/v1/CTCF/control/<string:command>/<int:ctcfId>', methods=['POST'])
References forward().
get_ctcf_telemetry()
routes.get_ctcf_telemetry (ctcfId)
Definition at line 234 of file routes.py.
def get_ctcf_telemetry(ctcfId):
    return forward(CTCF_API_BASE_URL,f"/telemetry/{ctcfId}", 'GET')
# NET-S Endpoints
@app.route('/api/v1/NETS/status', methods=['GET'])
References forward().
get_experiment_status()
routes.get_experiment_status ()
Definition at line 269 of file routes.py.
def get_experiment_status():
    return jsonify(experiment_status_store.get('status', {})), 200
get_gnb_configuration()
routes.get_gnb_configuration (gnbId)
CgNB Configuration Status Get the current CgNB configuration.
@brief Gets the current CgNB configuration.
@param gnbId The ID of the gNB.
@return JSON response with the current configuration.
Definition at line 92 of file routes.py.
def get_gnb_configuration(gnbId):
    """
    @brief Gets the current CgNB configuration.
    @param gnbId The ID of the gNB.
    @return JSON response with the current configuration.
    """
    return jsonify(cgnbcf_data_store.get(gnbId, {}).get('gnb_configuration', {})), 200
get_gnb_placement_status()
routes.get_gnb_placement_status (gnbId)
Definition at line 91 of file routes.py.
def get_gnb_placement_status(gnbId):
    return forward(CgNBCF_API_BASE_URL,'/configuration/{gnbId}', 'GET',)
@app.route('/api/v1/gNB/placement-setup/<int:gnbId>', methods=['POST'])
References forward().
get_gnb_radio_communications_status()
routes.get_gnb_radio_communications_status (gnbId)
Definition at line 99 of file routes.py.
def get_gnb_radio_communications_status(gnbId):
    return jsonify(gnb_data_store.get(gnbId, {}).get('radio_communications_status', {})), 200
@app.route('/api/v1/gNB/radiocommunications-setup/<int:gnbId>', methods=['POST'])
get_gnb_radio_sensing_status()
routes.get_gnb_radio_sensing_status (gnbId)
Definition at line 108 of file routes.py.
def get_gnb_radio_sensing_status(gnbId):
    return jsonify(gnb_data_store.get(gnbId, {}).get('radio_sensing_status', {})), 200
@app.route('/api/v1/gNB/radiosensing-setup/<int:gnbId>', methods=['POST'])
get_gnb_status()
routes.get_gnb_status (gnbId)
CgNB Status Get the current CgNB status.
@brief Gets the current CgNB status.
@param gnbId The ID of the gNB.
@return JSON response with the current status.
Definition at line 103 of file routes.py.
def get_gnb_status(gnbId):
    """
    @brief Gets the current CgNB status.
    @param gnbId The ID of the gNB.
    @return JSON response with the current status.
    """
    return jsonify(cgnbcf_data_store.get(gnbId, {}).get('gnb_status', {})), 200
get_gnb_video_sensing_status()
routes.get_gnb_video_sensing_status (gnbId)
Definition at line 117 of file routes.py.
def get_gnb_video_sensing_status(gnbId):
    return jsonify(gnb_data_store.get(gnbId, {}).get('video_sensing_status', {})), 200
@app.route('/api/v1/gNB/videosensing-setup/<int:gnbId>', methods=['POST'])
get_gnb_xapp_status()
routes.get_gnb_xapp_status (id)
Definition at line 126 of file routes.py.
def get_gnb_xapp_status(id):
    return jsonify(gnb_data_store.get(id, {}).get('xapp_status', {})), 200
@app.route('/api/v1/gNB/xapp-setup/<int:id>', methods=['POST'])
get_lis_placement_status()
routes.get_lis_placement_status (lisId)
Definition at line 173 of file routes.py.
def get_lis_placement_status(lisId):
    return forward(CLISCF_API_BASE_URL, f"/configuration/placement/{lisId}/status", 'GET')
@app.route('/api/v1/LIS/placement-setup/<int:lisId>', methods=['POST'])
References forward().
get_lis_radio_communications_status()
routes.get_lis_radio_communications_status (lisId)
Definition at line 181 of file routes.py.
def get_lis_radio_communications_status(lisId):
    return forward(CLISCF_API_BASE_URL, f"/configuration/radio-comms/{lisId}/status", 'GET')
@app.route('/api/v1/LIS/radiocommunications-setup/<int:lisId>', methods=['POST'])
References forward().
get_lis_radio_sensing_status()
routes.get_lis_radio_sensing_status (lisId)
Definition at line 189 of file routes.py.
def get_lis_radio_sensing_status(lisId):
    return forward(CLISCF_API_BASE_URL, f"/configuration/radio-sensing/{lisId}/status", 'GET')
@app.route('/api/v1/LIS/radiosensing-setup/<int:lisId>', methods=['POST'])
References forward().
get_lis_video_sensing_status()
routes.get_lis_video_sensing_status (lisId)
Definition at line 197 of file routes.py.
def get_lis_video_sensing_status(lisId):
    return forward(CLISCF_API_BASE_URL, f"/configuration/video-sensing/{lisId}/status", 'GET')
@app.route('/api/v1/LIS/videosensing-setup/<int:lisId>', methods=['POST'])
References forward().
get_nets_status()
routes.get_nets_status ()
Definition at line 240 of file routes.py.
def get_nets_status():
    return jsonify({"status": "NET-S operational"}), 200
@app.route('/api/v1/NETS/setup', methods=['POST'])
get_placement_configuration()
routes.get_placement_configuration (lisId)
@brief Gets the current LIS placement configuration.
@param lisId The ID of the LIS.
@return JSON response with the current configuration.
Definition at line 98 of file routes.py.
def get_placement_configuration(lisId):
    """
    @brief Gets the current LIS placement configuration.
    @param lisId The ID of the LIS.
    @return JSON response with the current configuration.
    """
    return jsonify(cliscf_data_store.get(lisId, {}).get('placement_configuration', {})), 200
@app.route('/configuration/placement/<int:lisId>/status', methods=['GET'])
get_placement_status()
routes.get_placement_status (lisId)
@brief Gets the current LIS placement status.
@param lisId The ID of the LIS.
@return JSON response with the current status.
Definition at line 107 of file routes.py.
def get_placement_status(lisId):
    """
    @brief Gets the current LIS placement status.
    @param lisId The ID of the LIS.
    @return JSON response with the current status.
    """
    return jsonify(cliscf_data_store.get(lisId, {}).get('placement_status', {})), 200
@app.route('/control/radio-comms/<int:lisId>/<string:command>', methods=['POST'])
get_radio_comms_configuration()
routes.get_radio_comms_configuration (lisId)
@brief Gets the LIS radio communication configuration.
@param lisId The ID of the LIS.
@return JSON response with the current configuration.
Definition at line 149 of file routes.py.
def get_radio_comms_configuration(lisId):
    """
    @brief Gets the LIS radio communication configuration.
    @param lisId The ID of the LIS.
    @return JSON response with the current configuration.
    """
    return jsonify(cliscf_data_store.get(lisId, {}).get('radio_comms_configuration', {})), 200
@app.route('/configuration/radio-comms/<int:lisId>/status', methods=['GET'])
get_radio_comms_status()
routes.get_radio_comms_status (lisId)
@brief Gets the LIS radio communication status.
@param lisId The ID of the LIS.
@return JSON response with the current status.
Definition at line 158 of file routes.py.
def get_radio_comms_status(lisId):
    """
    @brief Gets the LIS radio communication status.
    @param lisId The ID of the LIS.
    @return JSON response with the current status.
    """
    return jsonify(cliscf_data_store.get(lisId, {}).get('radio_comms_status', {})), 200
@app.route('/control/radio-sensing/<int:lisId>/<string:command>', methods=['POST'])
get_radio_sensing_status()
routes.get_radio_sensing_status (lisId)
@brief Gets the LIS radio sensing status.
@param lisId The ID of the LIS.
@return JSON response with the current status.
Definition at line 190 of file routes.py.
def get_radio_sensing_status(lisId):
    """
    @brief Gets the LIS radio sensing status.
    @param lisId The ID of the LIS.
    @return JSON response with the current status.
    """
    return jsonify(cliscf_data_store.get(lisId, {}).get('radio_sensing_status', {})), 200
get_traffic_control_rules()
routes.get_traffic_control_rules (ctcfId)
Get the current traffic control rules configuration.
Parameters
ctcfId The ID of the CTCF.
Returns
JSON response with the current configuration.
Definition at line 87 of file routes.py.
def get_traffic_control_rules(ctcfId):
    return jsonify(ctcf_data_store.get(ctcfId, {}).get('ctcf_rules', {})), 200
get_traffic_statistics()
routes.get_traffic_statistics (ctcfId)
Get statistics related to traffic control.
Parameters
ctcfId The ID of the CTCF.
Returns
JSON response with the current statistics.
Definition at line 102 of file routes.py.
def get_traffic_statistics(ctcfId):
    return jsonify(ctcf_data_store.get(ctcfId, {}).get('traffic_statistics', {})), 200
get_ue_configuration()
routes.get_ue_configuration (ueId)
Get the current CUE configuration.
Parameters
ueId The ID of the UE.
Returns
JSON response with the current configuration.
Definition at line 79 of file routes.py.
def get_ue_configuration(ueId):
    return jsonify(cuecf_data_store.get(ueId, {}).get('ue_configuration', {})), 200
get_ue_placement_status()
routes.get_ue_placement_status (ueId)
Definition at line 136 of file routes.py.
def get_ue_placement_status(ueId):
    return jsonify(ue_data_store.get(ueId, {}).get('placement_status', {})), 200
@app.route('/api/v1/UE/placement-setup/<int:ueId>', methods=['POST'])
get_ue_radio_communications_status()
routes.get_ue_radio_communications_status (ueId)
Definition at line 145 of file routes.py.
def get_ue_radio_communications_status(ueId):
    return jsonify(ue_data_store.get(ueId, {}).get('radio_communications_status', {})), 200
@app.route('/api/v1/UE/radiocommunications-setup/<int:ueId>', methods=['POST'])
get_ue_radio_sensing_status()
routes.get_ue_radio_sensing_status (ueId)
Definition at line 154 of file routes.py.
def get_ue_radio_sensing_status(ueId):
    return jsonify(ue_data_store.get(ueId, {}).get('radio_sensing_status', {})), 200
@app.route('/api/v1/UE/radiosensing-setup/<int:ueId>', methods=['POST'])
get_ue_status()
routes.get_ue_status (ueId)
Get the current CUE status.
Parameters
ueId The ID of the UE.
Returns
JSON response with the current status.
Definition at line 86 of file routes.py.
def get_ue_status(ueId):
    return jsonify(cuecf_data_store.get(ueId, {}).get('ue_status', {})), 200
get_ue_video_sensing_status()
routes.get_ue_video_sensing_status (ueId)
Definition at line 163 of file routes.py.
def get_ue_video_sensing_status(ueId):
    return jsonify(ue_data_store.get(ueId, {}).get('video_sensing_status', {})), 200
@app.route('/api/v1/UE/videosensing-setup/<int:ueId>', methods=['POST'])
get_vision_model_configuration()
routes.get_vision_model_configuration (modelId)
Get support vision model configuration.
Parameters
modelId The ID of the vision model.
Returns
JSON response with the current configuration.
Definition at line 121 of file routes.py.
def get_vision_model_configuration(modelId):
    return jsonify(vm_data_store.get(modelId, {}).get('vision_model_configuration', {})), 200
get_vision_model_status()
routes.get_vision_model_status (modelId)
Get support vision model status.
Parameters
modelId The ID of the vision model.
Returns
JSON response with the current status.
Definition at line 128 of file routes.py.
def get_vision_model_status(modelId):
    return jsonify(vm_data_store.get(modelId, {}).get('vision_model_status', {})), 200
gnb_control_start()
routes.gnb_control_start (command, gnbId)
CgNB Start/Stop CgNB sends Start/Stop command to NT-RIC, O-CU, O-DU and O-RU.
@brief Sends start/stop command to NT-RIC, O-CU, O-DU, and O-RU.
@param command The command to execute (start/stop).
@param gnbId The ID of the gNB.
@return JSON response with the result of the command.
Definition at line 77 of file routes.py.
def gnb_control_start(command, gnbId):
    """
    @brief Sends start/stop command to NT-RIC, O-CU, O-DU, and O-RU.
    @param command The command to execute (start/stop).
    @param gnbId The ID of the gNB.
    @return JSON response with the result of the command.
    """
    if command not in ['start', 'stop']:
        return bad_request("Invalid command")
    cgnbcf_data_store.setdefault(gnbId, {})['gnb_control'] = command
    return jsonify({"result": f"gNB control {command} command executed successfully"}), 201
References bad_request().
internal_error() [1/2]
routes.internal_error (error)
@brief Handles 500 errors.
@param error The error object.
@return JSON response with error details.
Definition at line 57 of file routes.py.
def internal_error(error):
    problem = {
        'error' : {
            'type' : "",
            'title' : "Internal Server Error",
            'status' : 500,
            'detail' : "An unexpected error occurred on the server.",
            'instance' : request.url
        }
    }
    return jsonify(problem), 500
internal_error() [2/2]
routes.internal_error (error)
@brief Handles 500 errors.
@param error The error object.
@return JSON response with error details.
Definition at line 57 of file routes.py.
def internal_error(error):
    """
    @brief Handles 500 errors.
    @param error The error object.
    @return JSON response with error details.
    """
    problem = {
        'error': {
            'type': "",
            'title': "Internal Server Error",
            'status': 500,
            'detail': "An unexpected error occurred on the server.",
            'instance': request.url
        }
    }
    return jsonify(problem), 500
@app.route('/control/placement/<int:lisId>/<string:command>', methods=['POST'])
not_found() [1/2]
routes.not_found (error)
@brief Handles 404 errors.
@param error The error object.
@return JSON response with error details.
Definition at line 31 of file routes.py.
def not_found(error):
    problem = {
        'error' : {
            'type' : "",
            'title' : "Resource Not Found",
            'status' : 404,
            'detail' : "The resource you requested was not found.",
            'instance' : request.url
        }
    }
    return jsonify(problem), 404
@app.errorhandler(400)
not_found() [2/2]
routes.not_found (error)
@brief Handles 404 errors.
@param error The error object.
@return JSON response with error details.
Definition at line 21 of file routes.py.
def not_found(error):
    """
    @brief Handles 404 errors.
    @param error The error object.
    @return JSON response with error details.
    """
    problem = {
        'error': {
            'type': "",
            'title': "Resource Not Found",
            'status': 404,
            'detail': "The resource you requested was not found.",
            'instance': request.url
        }
    }
    return jsonify(problem), 404
@app.errorhandler(400)
radio_comms_feedback()
routes.radio_comms_feedback (lisId)
@brief Enables the provision of feedback in terms of UE received power, to allow for automatic beam calibration.
@param lisId The ID of the LIS.
@return JSON response with the result of the feedback.
Definition at line 139 of file routes.py.
def radio_comms_feedback(lisId):
    """
    @brief Enables the provision of feedback in terms of UE received power, to allow for automatic beam calibration.
    @param lisId The ID of the LIS.
    @return JSON response with the result of the feedback.
    """
    cliscf_data_store.setdefault(lisId, {})['radio_comms_feedback'] = request.json
    return jsonify({"result": "Radio communications feedback received"}), 201
@app.route('/configuration/radio-comms/<int:lisId>', methods=['GET'])
setup_ctcf_rules()
routes.setup_ctcf_rules (ctcfId)
Definition at line 229 of file routes.py.
def setup_ctcf_rules(ctcfId):
    ctcf_data_store.setdefault(ctcfId, {})['rules'] = request.json
    return forward(CTCF_API_BASE_URL,f"/configuration/{ctcfId}/rules", 'POST', request.json)
@app.route('/api/v1/CTCF/telemetry/<int:ctcfId>', methods=['GET'])
References forward().
setup_gnb_placement()
routes.setup_gnb_placement (gnbId)
Definition at line 95 of file routes.py.
def setup_gnb_placement(gnbId):
    return forward(CgNBCF_API_BASE_URL,'/configuration/{gnbId}', 'POST', request.json)
@app.route('/api/v1/gNB/radiocommunications-status/<int:gnbId>', methods=['GET'])
References forward().
setup_gnb_radio_communications()
routes.setup_gnb_radio_communications (gnbId)
Definition at line 103 of file routes.py.
def setup_gnb_radio_communications(gnbId):
    gnb_data_store.setdefault(gnbId, {})['radio_communications_status'] = request.json
    return jsonify({"result": "gNB radio communications setup successful"}), 201
@app.route('/api/v1/gNB/radiosensing-status/<int:gnbId>', methods=['GET'])
setup_gnb_radio_sensing()
routes.setup_gnb_radio_sensing (gnbId)
Definition at line 112 of file routes.py.
def setup_gnb_radio_sensing(gnbId):
    gnb_data_store.setdefault(gnbId, {})['radio_sensing_status'] = request.json
    return jsonify({"result": "gNB radio sensing setup successful"}), 201
@app.route('/api/v1/gNB/videosensing-status/<int:gnbId>', methods=['GET'])
setup_gnb_video_sensing()
routes.setup_gnb_video_sensing (gnbId)
Definition at line 121 of file routes.py.
def setup_gnb_video_sensing(gnbId):
    gnb_data_store.setdefault(gnbId, {})['video_sensing_status'] = request.json
    return jsonify({"result": "gNB video sensing setup successful"}), 201
@app.route('/api/v1/gNB/xapp-status/<int:id>', methods=['GET'])
setup_lis_placement()
routes.setup_lis_placement (lisId)
Definition at line 177 of file routes.py.
def setup_lis_placement(lisId):
    return forward(CLISCF_API_BASE_URL, f"/configuration/placement/{lisId}", 'POST', request.json)
@app.route('/api/v1/LIS/radiocommunications-status/<int:lisId>', methods=['GET'])
References forward().
setup_lis_radio_communications()
routes.setup_lis_radio_communications (lisId)
Definition at line 185 of file routes.py.
def setup_lis_radio_communications(lisId):
    return forward(CLISCF_API_BASE_URL, f"/configuration/radio-comms/{lisId}", 'POST', request.json)
@app.route('/api/v1/LIS/radiosensing-status/<int:lisId>', methods=['GET'])
References forward().
setup_lis_radio_sensing()
routes.setup_lis_radio_sensing (lisId)
Definition at line 193 of file routes.py.
def setup_lis_radio_sensing(lisId):
    return forward(CLISCF_API_BASE_URL, f"/configuration/radio-sensing/{lisId}", 'POST', request.json)
@app.route('/api/v1/LIS/videosensing-status/<int:lisId>', methods=['GET'])
References forward().
setup_lis_video_sensing()
routes.setup_lis_video_sensing (lisId)
Definition at line 201 of file routes.py.
def setup_lis_video_sensing(lisId):
    return forward(CLISCF_API_BASE_URL,f"/configuration/video-sensing/{lisId}", 'POST', request.json)
# CTCF Endpoints
@app.route('/api/v1/CTCF/status/<int:ctcfId>', methods=['GET'])
References forward().
setup_nets()
routes.setup_nets ()
Definition at line 244 of file routes.py.
def setup_nets():
    return jsonify({"result": "NET-S setup successful"}), 201
# ML Model Endpoints
@app.route('/api/v1/ML/upload', methods=['POST'])
setup_ue_placement()
routes.setup_ue_placement (ueId)
Definition at line 140 of file routes.py.
def setup_ue_placement(ueId):
    ue_data_store.setdefault(ueId, {})['placement_status'] = request.json
    return jsonify({"result": "UE placement setup successful"}), 201
@app.route('/api/v1/UE/radiocommunications-status/<int:ueId>', methods=['GET'])
setup_ue_radio_communications()
routes.setup_ue_radio_communications (ueId)
Definition at line 149 of file routes.py.
def setup_ue_radio_communications(ueId):
    ue_data_store.setdefault(ueId, {})['radio_communications_status'] = request.json
    return jsonify({"result": "UE radio communications setup successful"}), 201
@app.route('/api/v1/UE/radiosensing-status/<int:ueId>', methods=['GET'])
setup_ue_radio_sensing()
routes.setup_ue_radio_sensing (ueId)
Definition at line 158 of file routes.py.
def setup_ue_radio_sensing(ueId):
    ue_data_store.setdefault(ueId, {})['radio_sensing_status'] = request.json
    return jsonify({"result": "UE radio sensing setup successful"}), 201
@app.route('/api/v1/UE/videosensing-status/<int:ueId>', methods=['GET'])
setup_ue_video_sensing()
routes.setup_ue_video_sensing (ueId)
Definition at line 167 of file routes.py.
def setup_ue_video_sensing(ueId):
    ue_data_store.setdefault(ueId, {})['video_sensing_status'] = request.json
    return jsonify({"result": "UE video sensing setup successful"}), 201
# LIS Endpoints
@app.route('/api/v1/LIS/placement-status/<int:lisId>', methods=['GET'])
traffic_control_start()
routes.traffic_control_start (command, ctcfId)
CTCF sends a start/stop command to control traffic servers.
Parameters
command The command to execute (start/stop).
ctcfId The ID of the CTCF.
Returns
JSON response with the result of the command.
Definition at line 77 of file routes.py.
def traffic_control_start(command, ctcfId):
    if command not in ['start', 'stop']:
        return bad_request("Invalid command")
    ctcf_data_store.setdefault(ctcfId, {})['traffic_control'] = command
    return jsonify({"result": f"Traffic Control {command} command executed successfully"}), 201
References bad_request().
ue_control_start()
routes.ue_control_start (command, ueId)
CUECF sends Start/Stop command via CUE interface to the relevant UE.
Parameters
command The command to execute (start/stop).
ueId The ID of the UE.
Returns
JSON response with the result of the command.
Definition at line 69 of file routes.py.
def ue_control_start(command, ueId):
    if command not in ['start', 'stop']:
        return bad_request("Invalid command")
    cuecf_data_store.setdefault(ueId, {})['ue_control'] = command
    return jsonify({"result": f"UE control {command} command executed successfully"}), 201
References bad_request().
upload_gnb_xapp()
routes.upload_gnb_xapp (id)
Definition at line 130 of file routes.py.
def upload_gnb_xapp(id):
    gnb_data_store.setdefault(id, {})['xapp_status'] = request.json
    return jsonify({"result": "gNB x-APP upload successful"}), 201
# UE Endpoints
@app.route('/api/v1/UE/placement-status/<int:ueId>', methods=['GET'])
upload_ml_model()
routes.upload_ml_model ()
Definition at line 249 of file routes.py.
def upload_ml_model():
    ml_model_store['model'] = request.json
    return jsonify({"result": "ML model upload successful"}), 201
@app.route('/api/v1/ML/download', methods=['GET'])
upload_odr_dataset()
routes.upload_odr_dataset ()
Definition at line 263 of file routes.py.
def upload_odr_dataset():
    odr_dataset_store['dataset'] = request.json
    return jsonify({"result": "ODR dataset upload successful"}), 201
# Experiment Status Endpoint
@app.route('/api/v1/CBF/status', methods=['GET'])
visual_model_control_start()
routes.visual_model_control_start (command, modelId)
CVCF sends a start/stop command to activate/deactivate support vision model.
Parameters
command The command to execute (start/stop).
modelId The ID of the vision model.
Returns
JSON response with the result of the command.
Definition at line 103 of file routes.py.
def visual_model_control_start(command, modelId):
    if command not in ['start', 'stop']:
        return bad_request("Invalid command")
    vm_data_store.setdefault(modelId, {})['vision_model_control'] = command
    return jsonify({"result": f"Vision Model control {command} command executed successfully"}), 201
References bad_request().
Variable Documentation
app
routes.app = Flask(__name__)
Definition at line 4 of file routes.py.
CgNBCF_API_BASE_URL
str routes.CgNBCF_API_BASE_URL = "http://localhost:5003"
Definition at line 27 of file routes.py.
cgnbcf_data_store
dict routes.cgnbcf_data_store
Initial value:
=  {
    1 : {
        'gnb_control' : 'stop',
        'gnb_configuration' : '',
        'gnb_telemetry': '',
    }
}
Definition at line 10 of file routes.py.
CLISCF_API_BASE_URL
str routes.CLISCF_API_BASE_URL = "http://localhost:5001"
Definition at line 25 of file routes.py.
cliscf_data_store
dict routes.cliscf_data_store
Initial value:
=  {
    0: {
        'placement_status': 'RUNNING'
    },
    1: {
        'placement_status': 'READY'
    },
}
Definition at line 10 of file routes.py.
CTCF_API_BASE_URL
str routes.CTCF_API_BASE_URL = "http://localhost:5002"
Definition at line 26 of file routes.py.
ctcf_data_store
dict routes.ctcf_data_store = {}
Definition at line 19 of file routes.py.
debug
routes.debug
Definition at line 273 of file routes.py.
experiment_status_store
dict routes.experiment_status_store = {}
Definition at line 23 of file routes.py.
gnb_data_store
dict routes.gnb_data_store
Initial value:
=  {
    0 : {
        'placement_status' : 'OK'
    },
    1 : {
        'placement_status' : 'FAILED'
    }
}
Definition at line 7 of file routes.py.
ml_model_store
dict routes.ml_model_store = {}
Definition at line 21 of file routes.py.
odr_dataset_store
dict routes.odr_dataset_store = {}
Definition at line 22 of file routes.py.
simulator_data_store
dict routes.simulator_data_store = {}
Definition at line 20 of file routes.py.
ue_data_store
dict routes.ue_data_store
Initial value:
=  {
}
Definition at line 16 of file routes.py.